# Generated by Django 3.1.3 on 2021-01-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuits', '0002_auto_20210113_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuits',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除'),
        ),
    ]
