# Generated by Django 3.1.3 on 2021-01-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugtalks',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除'),
        ),
    ]
